### ISSUE TITLE
support m4a extensions

### ISSUE THREAD

**Issue by drzraf** [souch/SMP#15]
maybe other are missing, didn"t check each and every supported format and possible extension

**Comment by souch** [comment]
Actually m4a should be supported.  [Android mediaplayer](https://developer.android.com/guide/appendix/media-formats.html) seems to support it, at least from Android 4.1+. What is your android version?

**Comment by drzraf** [comment]
4.4.2

the default media-player plays them without problem

**Comment by souch** [comment]
I tried playing m4a music using sicmuplayer on a 2.3 gingebread and it works fine. 
  [here is the file that work](http://dl.free.fr/mHCpTvBWc) no login, password: prata
In order to test it, you can send me if you want, your file that is not working using the same or similar service. You can tell me too if my file can be played on your device.

**Comment by drzraf** [comment]
The original report was about the m4a file not being displayed in the tree. I believed this was due to the file extension. But I just did a new test and m4a files appear (and are played) correctly.
I can't reproduce the issue. Let's close it.

**Comment by souch** [comment]
ok, thanks for the quick feedback.
